name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List project files
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

   
      - name: Run E2E user flow tests
        run: npm run test-user-flow || true

      - name: Run functional tests
        run: npm run test-functional || true

      - name: Run regression tests
        run: npm run test-regression-default || true

    
      - name: Check reports folder
        run: ls -R reports || echo "⚠️ reports folder missing"

      - name: Check Allure results
        run: ls -R reports/allure-results || echo "⚠️ allure-results folder missing or empty"

  
      - name: Install Allure CLI
        run: npm install -g allure-commandline

 
      - name: Generate Allure report
        run: allure generate reports/allure-results --clean -o reports/allure-report || echo "⚠️ Allure report generation failed"


      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: reports/cucumber-report.html

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
