name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # ----------------------------
      # Run Regression Tests
      # ----------------------------
      - name: Run regression tests
        run: npm run test-regression-default || true

      # ----------------------------
      # Debug generated folders
      # ----------------------------
      - name: Check reports folder
        run: ls -R reports || echo "⚠️ reports folder missing"

      - name: Check Allure results
        run: ls -R reports/allure-results || echo "⚠️ allure-results folder missing or empty"

      # ----------------------------
      # Generate HTML report (Cucumber/Allure)
      # ----------------------------
      - name: Generate HTML report
        run: npm run generate-allure-report
      # ----------------------------
      # Upload Reports as Artifacts
      # ----------------------------

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report